//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bageldemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int rowid { get; set; }
        public Nullable<bool> is_valid { get; set; }
        public string mno { get; set; }
        public string mname { get; set; }
        public string pass_user { get; set; }
        public string role_no { get; set; }
        public string code_gender { get; set; }
        public string department_no { get; set; }
        public string title_no { get; set; }
        public Nullable<System.DateTime> date_onboard { get; set; }
        public Nullable<System.DateTime> date_leave { get; set; }
        public string email_contact { get; set; }
        public string tel_contact { get; set; }
        public string addr_contact { get; set; }
        public string code_valid { get; set; }
        public string remark { get; set; }
    }
}
